# Generated by Django 3.1.7 on 2021-04-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('manual', 'Manual Exam'), ('mammogram', 'Mammogram'), ('ultrasound', 'Ultrasound'), ('mri', 'MRI'), ('biopsy', 'Lymph node biopsy')], max_length=25)),
                ('note', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=25)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
