# Generated by Django 3.1.7 on 2021-04-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='healthcare_professional',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=25),
        ),
    ]
