# Generated by Django 3.1.7 on 2021-05-11 12:01

from django.db import migrations, models
import django.db.models.deletion
import scancer.examinations.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_doctor'),
        ('examinations', '0002_auto_20210428_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('file', models.FilePathField(path=scancer.examinations.models.scan_images_path)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
