# Generated by Django 3.1.7 on 2021-05-12 13:21

from django.db import migrations, models
import scancer.examinations.models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_auto_20210511_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='scan',
            name='heatmap',
            field=models.FilePathField(blank=True, default='', path=scancer.examinations.models.analysis_images_path),
        ),
    ]
