# Generated by Django 3.1.7 on 2021-05-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_auto_20210512_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterField(
            model_name='examination',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(30, 'High'), (20, 'Medium'), (10, 'Low')], null=True),
        ),
    ]
