# Generated by Django 3.1.7 on 2021-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_number", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("NB", "Non-binary")],
                        max_length=5,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
            ],
        ),
    ]
