# Generated by Django 3.1.7 on 2021-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
