# Generated by Django 3.1.7 on 2021-05-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='risk',
            field=models.IntegerField(blank=True, choices=[(30, 'High'), (20, 'Medium'), (10, 'Low')]),
        ),
    ]
