# Generated by Django 3.1.7 on 2021-05-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20210513_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-risk']},
        ),
    ]
